// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: smallbox_output_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Output_Status int32

const (
	Output_AC  Output_Status = 0
	Output_WA  Output_Status = 1
	Output_RE  Output_Status = 2
	Output_TLE Output_Status = 3
	Output_MLE Output_Status = 4
	Output_UE  Output_Status = 5
)

// Enum value maps for Output_Status.
var (
	Output_Status_name = map[int32]string{
		0: "AC",
		1: "WA",
		2: "RE",
		3: "TLE",
		4: "MLE",
		5: "UE",
	}
	Output_Status_value = map[string]int32{
		"AC":  0,
		"WA":  1,
		"RE":  2,
		"TLE": 3,
		"MLE": 4,
		"UE":  5,
	}
)

func (x Output_Status) Enum() *Output_Status {
	p := new(Output_Status)
	*p = x
	return p
}

func (x Output_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Output_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_smallbox_output_message_proto_enumTypes[0].Descriptor()
}

func (Output_Status) Type() protoreflect.EnumType {
	return &file_smallbox_output_message_proto_enumTypes[0]
}

func (x Output_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Output_Status.Descriptor instead.
func (Output_Status) EnumDescriptor() ([]byte, []int) {
	return file_smallbox_output_message_proto_rawDescGZIP(), []int{0, 0}
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeUse   uint32        `protobuf:"varint,2,opt,name=time_use,json=timeUse,proto3" json:"time_use,omitempty"`
	MemoryUse uint32        `protobuf:"varint,3,opt,name=memory_use,json=memoryUse,proto3" json:"memory_use,omitempty"`
	Status    Output_Status `protobuf:"varint,4,opt,name=status,proto3,enum=Output_Status" json:"status,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smallbox_output_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_smallbox_output_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_smallbox_output_message_proto_rawDescGZIP(), []int{0}
}

func (x *Output) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Output) GetTimeUse() uint32 {
	if x != nil {
		return x.TimeUse
	}
	return 0
}

func (x *Output) GetMemoryUse() uint32 {
	if x != nil {
		return x.MemoryUse
	}
	return 0
}

func (x *Output) GetStatus() Output_Status {
	if x != nil {
		return x.Status
	}
	return Output_AC
}

var File_smallbox_output_message_proto protoreflect.FileDescriptor

var file_smallbox_output_message_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x6f, 0x78, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb6, 0x01, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x55, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f,
	0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x55, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x43, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x57, 0x41, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x45, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x54, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4c, 0x45, 0x10, 0x04,
	0x12, 0x06, 0x0a, 0x02, 0x55, 0x45, 0x10, 0x05, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_smallbox_output_message_proto_rawDescOnce sync.Once
	file_smallbox_output_message_proto_rawDescData = file_smallbox_output_message_proto_rawDesc
)

func file_smallbox_output_message_proto_rawDescGZIP() []byte {
	file_smallbox_output_message_proto_rawDescOnce.Do(func() {
		file_smallbox_output_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_smallbox_output_message_proto_rawDescData)
	})
	return file_smallbox_output_message_proto_rawDescData
}

var file_smallbox_output_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_smallbox_output_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smallbox_output_message_proto_goTypes = []interface{}{
	(Output_Status)(0), // 0: Output.Status
	(*Output)(nil),     // 1: Output
}
var file_smallbox_output_message_proto_depIdxs = []int32{
	0, // 0: Output.status:type_name -> Output.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_smallbox_output_message_proto_init() }
func file_smallbox_output_message_proto_init() {
	if File_smallbox_output_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smallbox_output_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smallbox_output_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smallbox_output_message_proto_goTypes,
		DependencyIndexes: file_smallbox_output_message_proto_depIdxs,
		EnumInfos:         file_smallbox_output_message_proto_enumTypes,
		MessageInfos:      file_smallbox_output_message_proto_msgTypes,
	}.Build()
	File_smallbox_output_message_proto = out.File
	file_smallbox_output_message_proto_rawDesc = nil
	file_smallbox_output_message_proto_goTypes = nil
	file_smallbox_output_message_proto_depIdxs = nil
}
