// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: smallbox_input_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input_Language int32

const (
	Input_c      Input_Language = 0
	Input_cpp    Input_Language = 1
	Input_golang Input_Language = 2
	Input_java   Input_Language = 3
	Input_python Input_Language = 4
	Input_rust   Input_Language = 5
)

// Enum value maps for Input_Language.
var (
	Input_Language_name = map[int32]string{
		0: "c",
		1: "cpp",
		2: "golang",
		3: "java",
		4: "python",
		5: "rust",
	}
	Input_Language_value = map[string]int32{
		"c":      0,
		"cpp":    1,
		"golang": 2,
		"java":   3,
		"python": 4,
		"rust":   5,
	}
)

func (x Input_Language) Enum() *Input_Language {
	p := new(Input_Language)
	*p = x
	return p
}

func (x Input_Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Input_Language) Descriptor() protoreflect.EnumDescriptor {
	return file_smallbox_input_message_proto_enumTypes[0].Descriptor()
}

func (Input_Language) Type() protoreflect.EnumType {
	return &file_smallbox_input_message_proto_enumTypes[0]
}

func (x Input_Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Input_Language.Descriptor instead.
func (Input_Language) EnumDescriptor() ([]byte, []int) {
	return file_smallbox_input_message_proto_rawDescGZIP(), []int{0, 0}
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashName string         `protobuf:"bytes,1,opt,name=hash_name,json=hashName,proto3" json:"hash_name,omitempty"`
	Lang     Input_Language `protobuf:"varint,2,opt,name=lang,proto3,enum=Input_Language" json:"lang,omitempty"`
	Time     uint32         `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Memory   uint32         `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Cases    []*Case        `protobuf:"bytes,5,rep,name=cases,proto3" json:"cases,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smallbox_input_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_smallbox_input_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_smallbox_input_message_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetHashName() string {
	if x != nil {
		return x.HashName
	}
	return ""
}

func (x *Input) GetLang() Input_Language {
	if x != nil {
		return x.Lang
	}
	return Input_c
}

func (x *Input) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Input) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Input) GetCases() []*Case {
	if x != nil {
		return x.Cases
	}
	return nil
}

type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	In  string `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	Out string `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smallbox_input_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_smallbox_input_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_smallbox_input_message_proto_rawDescGZIP(), []int{1}
}

func (x *Case) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Case) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Case) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_smallbox_input_message_proto protoreflect.FileDescriptor

var file_smallbox_input_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda,
	0x01, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x63, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x05, 0x63, 0x61,
	0x73, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x05, 0x0a, 0x01, 0x63, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x70, 0x70, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x6a,
	0x61, 0x76, 0x61, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10,
	0x04, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x75, 0x73, 0x74, 0x10, 0x05, 0x22, 0x38, 0x0a, 0x04, 0x43,
	0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x75, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smallbox_input_message_proto_rawDescOnce sync.Once
	file_smallbox_input_message_proto_rawDescData = file_smallbox_input_message_proto_rawDesc
)

func file_smallbox_input_message_proto_rawDescGZIP() []byte {
	file_smallbox_input_message_proto_rawDescOnce.Do(func() {
		file_smallbox_input_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_smallbox_input_message_proto_rawDescData)
	})
	return file_smallbox_input_message_proto_rawDescData
}

var file_smallbox_input_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_smallbox_input_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smallbox_input_message_proto_goTypes = []interface{}{
	(Input_Language)(0), // 0: Input.Language
	(*Input)(nil),       // 1: Input
	(*Case)(nil),        // 2: Case
}
var file_smallbox_input_message_proto_depIdxs = []int32{
	0, // 0: Input.lang:type_name -> Input.Language
	2, // 1: Input.cases:type_name -> Case
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_smallbox_input_message_proto_init() }
func file_smallbox_input_message_proto_init() {
	if File_smallbox_input_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smallbox_input_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smallbox_input_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smallbox_input_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smallbox_input_message_proto_goTypes,
		DependencyIndexes: file_smallbox_input_message_proto_depIdxs,
		EnumInfos:         file_smallbox_input_message_proto_enumTypes,
		MessageInfos:      file_smallbox_input_message_proto_msgTypes,
	}.Build()
	File_smallbox_input_message_proto = out.File
	file_smallbox_input_message_proto_rawDesc = nil
	file_smallbox_input_message_proto_goTypes = nil
	file_smallbox_input_message_proto_depIdxs = nil
}
