// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sandbox/case_message.proto

package pb_sb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId uint32 `protobuf:"varint,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	In     string `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	Out    string `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_case_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_case_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_sandbox_case_message_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetCaseId() uint32 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

func (x *Case) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Case) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_sandbox_case_message_proto protoreflect.FileDescriptor

var file_sandbox_case_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x31,
	0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x22, 0x41, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x42, 0x34, 0x5a, 0x32, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74, 0x74, 0x2f,
	0x73, 0x62, 0x2d, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x3b, 0x70, 0x62, 0x5f, 0x73,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sandbox_case_message_proto_rawDescOnce sync.Once
	file_sandbox_case_message_proto_rawDescData = file_sandbox_case_message_proto_rawDesc
)

func file_sandbox_case_message_proto_rawDescGZIP() []byte {
	file_sandbox_case_message_proto_rawDescOnce.Do(func() {
		file_sandbox_case_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandbox_case_message_proto_rawDescData)
	})
	return file_sandbox_case_message_proto_rawDescData
}

var file_sandbox_case_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sandbox_case_message_proto_goTypes = []interface{}{
	(*Case)(nil), // 0: v1.sandbox.Case
}
var file_sandbox_case_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_case_message_proto_init() }
func file_sandbox_case_message_proto_init() {
	if File_sandbox_case_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sandbox_case_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandbox_case_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandbox_case_message_proto_goTypes,
		DependencyIndexes: file_sandbox_case_message_proto_depIdxs,
		MessageInfos:      file_sandbox_case_message_proto_msgTypes,
	}.Build()
	File_sandbox_case_message_proto = out.File
	file_sandbox_case_message_proto_rawDesc = nil
	file_sandbox_case_message_proto_goTypes = nil
	file_sandbox_case_message_proto_depIdxs = nil
}
