// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sandbox/input_message.proto

package pb_sb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashName string   `protobuf:"bytes,1,opt,name=hash_name,json=hashName,proto3" json:"hash_name,omitempty"`
	Lang     Language `protobuf:"varint,2,opt,name=lang,proto3,enum=v1.sandbox.Language" json:"lang,omitempty"`
	Time     uint32   `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Memory   uint32   `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	MntPath  string   `protobuf:"bytes,5,opt,name=mnt_path,json=mntPath,proto3" json:"mnt_path,omitempty"`
	Cases    []*Case  `protobuf:"bytes,6,rep,name=cases,proto3" json:"cases,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_input_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_input_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_sandbox_input_message_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetHashName() string {
	if x != nil {
		return x.HashName
	}
	return ""
}

func (x *Input) GetLang() Language {
	if x != nil {
		return x.Lang
	}
	return Language_c
}

func (x *Input) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Input) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Input) GetMntPath() string {
	if x != nil {
		return x.MntPath
	}
	return ""
}

func (x *Input) GetCases() []*Case {
	if x != nil {
		return x.Cases
	}
	return nil
}

var File_sandbox_input_message_proto protoreflect.FileDescriptor

var file_sandbox_input_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76,
	0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x1a, 0x1a, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x6c,
	0x61, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd,
	0x01, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x6e, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x05, 0x63, 0x61, 0x73, 0x65, 0x73, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71,
	0x74, 0x74, 0x2f, 0x73, 0x62, 0x2d, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x3b, 0x70,
	0x62, 0x5f, 0x73, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sandbox_input_message_proto_rawDescOnce sync.Once
	file_sandbox_input_message_proto_rawDescData = file_sandbox_input_message_proto_rawDesc
)

func file_sandbox_input_message_proto_rawDescGZIP() []byte {
	file_sandbox_input_message_proto_rawDescOnce.Do(func() {
		file_sandbox_input_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandbox_input_message_proto_rawDescData)
	})
	return file_sandbox_input_message_proto_rawDescData
}

var file_sandbox_input_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sandbox_input_message_proto_goTypes = []interface{}{
	(*Input)(nil), // 0: v1.sandbox.Input
	(Language)(0), // 1: v1.sandbox.Language
	(*Case)(nil),  // 2: v1.sandbox.Case
}
var file_sandbox_input_message_proto_depIdxs = []int32{
	1, // 0: v1.sandbox.Input.lang:type_name -> v1.sandbox.Language
	2, // 1: v1.sandbox.Input.cases:type_name -> v1.sandbox.Case
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sandbox_input_message_proto_init() }
func file_sandbox_input_message_proto_init() {
	if File_sandbox_input_message_proto != nil {
		return
	}
	file_sandbox_case_message_proto_init()
	file_sandbox_lang_enum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sandbox_input_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandbox_input_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandbox_input_message_proto_goTypes,
		DependencyIndexes: file_sandbox_input_message_proto_depIdxs,
		MessageInfos:      file_sandbox_input_message_proto_msgTypes,
	}.Build()
	File_sandbox_input_message_proto = out.File
	file_sandbox_input_message_proto_rawDesc = nil
	file_sandbox_input_message_proto_goTypes = nil
	file_sandbox_input_message_proto_depIdxs = nil
}
