// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sandbox/lang_enum.proto

package pb_sb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_c      Language = 0
	Language_cpp    Language = 1
	Language_golang Language = 2
	Language_java   Language = 3
	Language_python Language = 4
	Language_rust   Language = 5
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "c",
		1: "cpp",
		2: "golang",
		3: "java",
		4: "python",
		5: "rust",
	}
	Language_value = map[string]int32{
		"c":      0,
		"cpp":    1,
		"golang": 2,
		"java":   3,
		"python": 4,
		"rust":   5,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_lang_enum_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_sandbox_lang_enum_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_lang_enum_proto_rawDescGZIP(), []int{0}
}

var File_sandbox_lang_enum_proto protoreflect.FileDescriptor

var file_sandbox_lang_enum_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x31, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2a, 0x46, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x05, 0x0a, 0x01, 0x63, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x70, 0x70, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x6a, 0x61, 0x76, 0x61, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x79, 0x74, 0x68, 0x6f,
	0x6e, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x75, 0x73, 0x74, 0x10, 0x05, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74,
	0x74, 0x2f, 0x73, 0x62, 0x2d, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x3b, 0x70, 0x62,
	0x5f, 0x73, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sandbox_lang_enum_proto_rawDescOnce sync.Once
	file_sandbox_lang_enum_proto_rawDescData = file_sandbox_lang_enum_proto_rawDesc
)

func file_sandbox_lang_enum_proto_rawDescGZIP() []byte {
	file_sandbox_lang_enum_proto_rawDescOnce.Do(func() {
		file_sandbox_lang_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandbox_lang_enum_proto_rawDescData)
	})
	return file_sandbox_lang_enum_proto_rawDescData
}

var file_sandbox_lang_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_lang_enum_proto_goTypes = []interface{}{
	(Language)(0), // 0: v1.sandbox.Language
}
var file_sandbox_lang_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_lang_enum_proto_init() }
func file_sandbox_lang_enum_proto_init() {
	if File_sandbox_lang_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandbox_lang_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandbox_lang_enum_proto_goTypes,
		DependencyIndexes: file_sandbox_lang_enum_proto_depIdxs,
		EnumInfos:         file_sandbox_lang_enum_proto_enumTypes,
	}.Build()
	File_sandbox_lang_enum_proto = out.File
	file_sandbox_lang_enum_proto_rawDesc = nil
	file_sandbox_lang_enum_proto_goTypes = nil
	file_sandbox_lang_enum_proto_depIdxs = nil
}
