// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: judger/judger_message.proto

package pb_jg

import (
	sandbox "github.com/msqtt/sb-judger/api/pb/v1/sandbox"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编程语言
	Lang sandbox.Language `protobuf:"varint,1,opt,name=lang,proto3,enum=v1.sandbox.Language" json:"lang,omitempty"`
	// 程序源代码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 程序输入内容:w
	Input string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// 限定运行时间
	Time uint32 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	// 限定使用内存
	Memory uint32 `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judger_judger_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judger_judger_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_judger_judger_message_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetLang() sandbox.Language {
	if x != nil {
		return x.Lang
	}
	return sandbox.Language(0)
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunCodeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *RunCodeRequest) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RunCodeRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type RunCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 程序输出
	OutPut string `protobuf:"bytes,1,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
	// 程序耗时
	TimeUsage uint32 `protobuf:"varint,2,opt,name=time_usage,json=timeUsage,proto3" json:"time_usage,omitempty"`
	// 程序使用内存
	MemoryUsage uint32 `protobuf:"varint,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judger_judger_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judger_judger_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_judger_judger_message_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

func (x *RunCodeResponse) GetTimeUsage() uint32 {
	if x != nil {
		return x.TimeUsage
	}
	return 0
}

func (x *RunCodeResponse) GetMemoryUsage() uint32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type JudgeCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编程语言
	Lang sandbox.Language `protobuf:"varint,1,opt,name=lang,proto3,enum=v1.sandbox.Language" json:"lang,omitempty"`
	// 程序源代码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 限定运行时间
	Time uint32 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// 限定使用内存
	Memory uint32          `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Case   []*sandbox.Case `protobuf:"bytes,5,rep,name=case,proto3" json:"case,omitempty"`
}

func (x *JudgeCodeRequest) Reset() {
	*x = JudgeCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judger_judger_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeCodeRequest) ProtoMessage() {}

func (x *JudgeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judger_judger_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeCodeRequest.ProtoReflect.Descriptor instead.
func (*JudgeCodeRequest) Descriptor() ([]byte, []int) {
	return file_judger_judger_message_proto_rawDescGZIP(), []int{2}
}

func (x *JudgeCodeRequest) GetLang() sandbox.Language {
	if x != nil {
		return x.Lang
	}
	return sandbox.Language(0)
}

func (x *JudgeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JudgeCodeRequest) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *JudgeCodeRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *JudgeCodeRequest) GetCase() []*sandbox.Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type JudgeCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 程序状态
	Status sandbox.Status `protobuf:"varint,1,opt,name=status,proto3,enum=v1.sandbox.Status" json:"status,omitempty"`
	// 程序使用总时间
	TotalTimeUsage uint32 `protobuf:"varint,2,opt,name=total_time_usage,json=totalTimeUsage,proto3" json:"total_time_usage,omitempty"`
	// 程序使用总内存
	TotalMemoryUsage uint32 `protobuf:"varint,3,opt,name=total_memory_usage,json=totalMemoryUsage,proto3" json:"total_memory_usage,omitempty"`
}

func (x *JudgeCodeResponse) Reset() {
	*x = JudgeCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judger_judger_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeCodeResponse) ProtoMessage() {}

func (x *JudgeCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judger_judger_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeCodeResponse.ProtoReflect.Descriptor instead.
func (*JudgeCodeResponse) Descriptor() ([]byte, []int) {
	return file_judger_judger_message_proto_rawDescGZIP(), []int{3}
}

func (x *JudgeCodeResponse) GetStatus() sandbox.Status {
	if x != nil {
		return x.Status
	}
	return sandbox.Status(0)
}

func (x *JudgeCodeResponse) GetTotalTimeUsage() uint32 {
	if x != nil {
		return x.TotalTimeUsage
	}
	return 0
}

func (x *JudgeCodeResponse) GetTotalMemoryUsage() uint32 {
	if x != nil {
		return x.TotalMemoryUsage
	}
	return 0
}

var File_judger_judger_message_proto protoreflect.FileDescriptor

var file_judger_judger_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76,
	0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x1a, 0x17, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0e, 0x52, 0x75, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52,
	0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x6c, 0x0a, 0x0f, 0x52,
	0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x10, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x63, 0x61, 0x73, 0x65, 0x22, 0x97,
	0x01, 0x0a, 0x11, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x71, 0x74, 0x74, 0x2f, 0x73, 0x62, 0x2d,
	0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31,
	0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f, 0x6a, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_judger_judger_message_proto_rawDescOnce sync.Once
	file_judger_judger_message_proto_rawDescData = file_judger_judger_message_proto_rawDesc
)

func file_judger_judger_message_proto_rawDescGZIP() []byte {
	file_judger_judger_message_proto_rawDescOnce.Do(func() {
		file_judger_judger_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_judger_judger_message_proto_rawDescData)
	})
	return file_judger_judger_message_proto_rawDescData
}

var file_judger_judger_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_judger_judger_message_proto_goTypes = []interface{}{
	(*RunCodeRequest)(nil),    // 0: v1.judger.RunCodeRequest
	(*RunCodeResponse)(nil),   // 1: v1.judger.RunCodeResponse
	(*JudgeCodeRequest)(nil),  // 2: v1.judger.JudgeCodeRequest
	(*JudgeCodeResponse)(nil), // 3: v1.judger.JudgeCodeResponse
	(sandbox.Language)(0),     // 4: v1.sandbox.Language
	(*sandbox.Case)(nil),      // 5: v1.sandbox.Case
	(sandbox.Status)(0),       // 6: v1.sandbox.Status
}
var file_judger_judger_message_proto_depIdxs = []int32{
	4, // 0: v1.judger.RunCodeRequest.lang:type_name -> v1.sandbox.Language
	4, // 1: v1.judger.JudgeCodeRequest.lang:type_name -> v1.sandbox.Language
	5, // 2: v1.judger.JudgeCodeRequest.case:type_name -> v1.sandbox.Case
	6, // 3: v1.judger.JudgeCodeResponse.status:type_name -> v1.sandbox.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_judger_judger_message_proto_init() }
func file_judger_judger_message_proto_init() {
	if File_judger_judger_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_judger_judger_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judger_judger_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judger_judger_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judger_judger_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_judger_judger_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_judger_judger_message_proto_goTypes,
		DependencyIndexes: file_judger_judger_message_proto_depIdxs,
		MessageInfos:      file_judger_judger_message_proto_msgTypes,
	}.Build()
	File_judger_judger_message_proto = out.File
	file_judger_judger_message_proto_rawDesc = nil
	file_judger_judger_message_proto_goTypes = nil
	file_judger_judger_message_proto_depIdxs = nil
}
